appid: XXXXXXX  #此处是appid
partner: XXXXXXXXX  #此处是商户号
partnerkey: XXXXXXXX   #此处是商户平台的key
appsecret: XXXXXXXXX  #此处是商户平台的秘钥
notifyurl: http://a31ef7db.ngrok.io/WeChatPay/WeChatPayNotify
access_token_url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
grant_type: authorization_code
server:
  port: 80
  address: 0.0.0.0